### ISSUE TITLE
Orchestration Module Demo Video

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot-site#194]
## Description

HGP-33 (https://snapshot.org/#/hbot.eth/proposal/0x743f6d94a36dd4a70ab0bb64648c229f538ae0ff3ddd56da0fe47d90d2d920f7) allocated 1M HBOT toward community incentives for creating content and hosting events related to Hummingbot. 

Under this proposal, the Foundation is assigning two bounties to the Orchestration Module creator [TheHolyRoger](https://github.com/TheHolyRoger) to create videos that show how to set up and use the following integrations that use the new Orchestration Module :
* RogerThat: TradingView integration with Hummingbot
* HomeAssistant integration with Hummingbot

## Bounty

Sponsor: Hummingbot Foundation
Bounty amount: 100,000 HBOT
Developer portion: 100%
Status: Assigned to [TheHolyRoger](https://github.com/TheHolyRoger)

**Comment by TheHolyRoger** [comment]
👍

**Comment by fengtality** [comment]
@TheHolyRoger Any update on this?

**Comment by nikspz** [comment]
hi @TheHolyRoger Please add your updates here

**Comment by TheHolyRoger** [comment]
@nikspz @fengtality sorry still having health issues, will aim for later this week

**Comment by nikspz** [comment]
hi @TheHolyRoger Could you please add your updates/ timeframe when video be available for review here? Do you still want to work on this bounty? Thank you
