### ISSUE TITLE
Directional Strategy Experiment

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot-site#197]
## Description

Create a content that describes a directional strategy experiment, similar to [Strategy Experiment #1](https://blog.hummingbot.org/strategy-experiment-directional-trading-macd-bollinger-bands-indicators/):

* Create a custom Hummingbot script that uses the new, simplified directional strategy framework
* As examples, refer to the 3 directional strategy scripts in `development` branch: [directional_strategy_rsi.py](https://github.com/hummingbot/hummingbot/blob/development/scripts/directional_strategy_rsi.py), [directional_strategy_rsi_spot.py](https://github.com/hummingbot/hummingbot/blob/development/scripts/directional_strategy_rsi_spot.py), [directional_strategy_macd_bb.py](https://github.com/hummingbot/hummingbot/blob/development/scripts/directional_strategy_macd_bb.py)
* The script should conduct a strategy experiment similar to the one in the blog post above - formulate a hypothesis, define the pair/exchange, and define a success/failure outcome
* Run the bot with a small amount of real capital for at least 7 days
* Submit link to draft blog post or video in this issue

## Bounty

* Sponsor: Hummingbot Foundation
* Budget: [HGP-33](https://snapshot.org/#/hbot.eth/proposal/0x743f6d94a36dd4a70ab0bb64648c229f538ae0ff3ddd56da0fe47d90d2d920f7)
* Bounty: 100,000 HBOT OR 500 USDT
* Developer share: 100% - Paid upon publication
* Status: Open

**Comment by tomasgaudino** [comment]
I'd like to take this bounty please!

**Comment by nikspz** [comment]
Assigned to @tomasgaudino , please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by tomasgaudino** [comment]
Hi @nikspz ! Thanks for assigning me. The strategy is running from yesterday so by next wednesday i'll be showing the strategy fundamentals and results. Do you prefer a blog post or a video? I can communicate partial results via discord, please tell me in which channel

**Comment by nikspz** [comment]
About exactly Blog or Video that's not really matters, quality that's what is important. 
You should use this one as example: https://blog.hummingbot.org/strategy-experiment-directional-trading-macd-bollinger-bands-indicators/ 
You could read [Description ](https://github.com/hummingbot/hummingbot-site/issues/197#issue-1753616991 )again for more details. You should Create a new custom Hummingbot script that uses the new, simplified directional strategy framework.

About discord: You could create a group chat and add me there (Nikita B#7970)

**Comment by fengtality** [comment]
@tomasgaudino Any update on this?

**Comment by tomasgaudino** [comment]
hi there, yes. i'm finishing an explicative video with the strategy fundamentals and results, hope finishing by today

**Comment by tomasgaudino** [comment]
@fengtality i've sent via discord the results! please tell me how to proceed with the deliverables (video, strategy files, dashboard image if necessary, etc.)

**Comment by fengtality** [comment]
thanks looks great! please pass the original video file to our team so that
we can publish on our YouTube channel.

**Comment by tomasgaudino** [comment]
done :)

**Comment by fengtality** [comment]
Thanks @tomasgaudino - the video looks great. As watchers often ask for the underlying code, can you provide the code either as a gist or your Hummingbot fork. Afterwards, @carlitogetaladajr can add it to the Youtube video https://www.youtube.com/watch?v=UX0ChdWV7uc description.

**Comment by tomasgaudino** [comment]
Thank you for the opportunity! Absolutely, here is the link 

https://github.com/tomasgaudino/hummingbot/blob/feat/directional-strategy-macd-diff/scripts/directional_strategy_macd_diff.py 

Have a nice weekend!
