### ISSUE TITLE
Grid Strategy Experiment

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot-site#202]
## Description

Create a content that describes a strategy experiment on a grid-style trading strategy, similar to [Strategy Experiment #1](https://blog.hummingbot.org/strategy-experiment-directional-trading-macd-bollinger-bands-indicators/):

* Create a custom Hummingbot script implements a strategy similar to the original [Fixed Grid](https://medium.com/@rkc2000/introducing-the-fixed-grid-strategy-for-hummingbot-d9b011c71e9b) strategy
* The script should conduct a strategy experiment similar to the one in the blog post above - formulate a hypothesis, define the pair/exchange, and define a success/failure outcome
* Run the grid bot with a small amount of real capital for at least 7 days
* Submit link to draft blog post or video in this issue

## Bounty

* Sponsor: Hummingbot Foundation
* Budget: [HGP-33](https://snapshot.org/#/hbot.eth/proposal/0x743f6d94a36dd4a70ab0bb64648c229f538ae0ff3ddd56da0fe47d90d2d920f7)
* Bounty: 100,000 HBOT
* Developer share: 100% - Paid upon publication
* Status: Assigned to rkc2000, author of the fixed-grid stategy

**Comment by rkc2000** [comment]
Assign this to me please.

**Comment by nikspz** [comment]
Assigned to @rkc2000 , please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by nikspz** [comment]
hi @rkc2000 Could you please add your updates about Grid strategy bounty here?

**Comment by rkc2000** [comment]
Hi, i will submit the script for fixed grid along with a video soon.. I'm just waiting on a live run to complete so I can use a recent example in the video

**Comment by rkc2000** [comment]
Here's the link to a video describing the strategy: https://drive.google.com/file/d/1TGIugOU_N2vXy858CSIwD_FggBaEif0s/view?usp=drive_link

**Comment by nikspz** [comment]
Thanks, looks like video are currently uploading/processing. 
Could you please give a link for a `script` to check as well? @rkc2000

**Comment by rkc2000** [comment]
Yes, I am submitting a PR. Or shall I just provide a link to it?

**Comment by nikspz** [comment]
Yep, a link or a file @rkc2000

**Comment by nikspz** [comment]
Cool, thank you, video looks great 👍,will check with the team and review @rkc2000

**Comment by nikspz** [comment]
Sorry, @rkc2000 could you please create the PR to add the script to the /scripts/ folder, pointing to the development branch? Thank you

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @rkc2000. The video recorded and released (https://www.youtube.com/watch?v=1j81gP2ToCE) and script has been deployed on development branch (dev-1.19.0) and next hummingbot version 1.19.0.
