### ISSUE TITLE
Link for bscscan Official Foundation Bounty Wallets

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot-site#357]
https://hummingbot.org/bounties/sponsors/#official-foundation-bounty-wallets

Actual:
current link is https://bscscan.com/address/0xe517b826a26b439ece92f3220628c007049d915

Expected:
should be https://bscscan.com/address/0xE517b826a26B439eCE92f3220628eC007049d915

0xE517b826a26B439eCE92f3220628eC007049d915

**Comment by fengtality** [comment]
https://github.com/hummingbot/hummingbot-site/commit/b5e0f5681ac73fe7f5b388c4463e56a69e258513
